### PR TITLE
Upgrade shell js to latest version

### PR DESCRIPTION
**Pull request by kchitalia**

### CODE REVIEW

**Comment by bhariharan** [comment]
👍

**Comment by wmathurin** [comment]
Do we actually require 0.7.0 or will it work with any version of shelljs ?

**Comment by kchitalia** [comment]
It should work for all versions. But I thought we wanted to upgrade to the latest version of shelljs.

**Comment by wmathurin** [comment]
We want it to work with the latest version but it's nice to hear that it should work with older versions as well.

**Comment by wmathurin** [comment]
test_force.js should only check that shelljs is there.
We should be able to run test_force.js with different version of shelljs (for coverage).

**Comment by kchitalia** [comment]
Thats what I was thinking too. I'll remove the check for version.

**Pull request merged**
