### PR TITLE
Default api version was a bit out dated

### PR DESCRIPTION
**Pull request by wmathurin**

### CODE REVIEW

**Comment by bhariharan** [comment]
Might be safer to do this on ```unstable``` first, just in case some API behavior has changed in ```v36.0```. Is ```v36.0``` live on all instances?

**Comment by bhariharan** [comment]
Do we need this for the patch release?

**Comment by wmathurin** [comment]
We don't need it, but it would be nice to keep the default to the latest production release. Does it create more work for the patch?

**Comment by bhariharan** [comment]
Sure - if it's live on all instances, we can get in in. :+1:

**Comment by rwhitley** [comment]
It is live on all instances.

On Mon, Feb 22, 2016 at 4:15 PM, Bharath Hariharan <notifications@github.com
> wrote:

> Merged #338
> <https://github.com/forcedotcom/SalesforceMobileSDK-Shared/pull/338>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forcedotcom/SalesforceMobileSDK-Shared/pull/338#event-560677271>
> .
>



-- 
Richard

**Pull request merged**
